<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Filme;

class FilmeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Filme::insert([
            [
                'titulo' => 'Interestelar',
                'diretor' => 'Christopher Nolan',
                'ano' => 2014,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Um grupo de astronautas atravessa um buraco de minhoca em busca de um novo lar para a humanidade.',
                'capa' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
            ],
            [
                'titulo' => 'O Poderoso Chefão',
                'diretor' => 'Francis Ford Coppola',
                'ano' => 1972,
                'genero' => 'Crime',
                'sinopse' => 'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império para seu filho relutante.',
                'capa' => 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            ],
            [
                'titulo' => 'Batman: O Cavaleiro das Trevas',
                'diretor' => 'Christopher Nolan',
                'ano' => 2008,
                'genero' => 'Ação',
                'sinopse' => 'Quando a ameaça conhecida como Coringa causa estragos e caos em Gotham, Batman deve aceitar um dos maiores testes psicológicos e físicos de sua capacidade de combater a injustiça.',
                'capa' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            ],
            [
                'titulo' => 'Pulp Fiction: Tempo de Violência',
                'diretor' => 'Quentin Tarantino',
                'ano' => 1994,
                'genero' => 'Crime',
                'sinopse' => 'As vidas de dois assassinos da máfia, um boxeador, a esposa de um gângster e dois assaltantes se entrelaçam em quatro histórias de violência e redenção.',
                'capa' => 'https://media.themoviedb.org/t/p/w300_and_h450_face/tptjnB2LDbuUWya9Cx5sQtv5hqb.jpg',
            ],
            [
                'titulo' => 'A Origem',
                'diretor' => 'Christopher Nolan',
                'ano' => 2010,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Um ladrão que rouba segredos corporativos através do uso da tecnologia de compartilhamento de sonhos recebe a tarefa inversa de plantar uma ideia na mente de um CEO.',
                'capa' => 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
            ],
            [
                'titulo' => 'Clube da Luta',
                'diretor' => 'David Fincher',
                'ano' => 1999,
                'genero' => 'Drama',
                'sinopse' => 'Um trabalhador de escritório insonomíaco e um sabão militar insatisfeito formam um clube de luta subterrâneo que evolui para algo muito maior.',
                'capa' => 'https://media.themoviedb.org/t/p/w94_and_h141_face/mCICnh7QBH0gzYaTQChBDDVIKdm.jpg',
            ],
            [
                'titulo' => 'Matrix',
                'diretor' => 'Lana Wachowski, Lilly Wachowski',
                'ano' => 1999,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Um hacker descobre pela mão de rebeldes misteriosos a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.',
                'capa' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            ],
            [
                'titulo' => 'Forrest Gump: O Contador de Histórias',
                'diretor' => 'Robert Zemeckis',
                'ano' => 1994,
                'genero' => 'Drama',
                'sinopse' => 'As presidências de Kennedy e Johnson, os eventos do Vietnã e Watergate se desdobram através da perspectiva de um homem do Alabama com QI de 75.',
                'capa' => 'https://media.themoviedb.org/t/p/w300_and_h450_face/d74WpIsH8379TIL4wUxDneRCYv2.jpg',
            ],
            [
                'titulo' => 'O Senhor dos Anéis: O Retorno do Rei',
                'diretor' => 'Peter Jackson',
                'ano' => 2003,
                'genero' => 'Fantasia',
                'sinopse' => 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para chamar sua atenção de Frodo e Sam enquanto eles se aproximam da Montanha da Perdição.',
                'capa' => 'https://media.themoviedb.org/t/p/w300_and_h450_face/b5pl6GmQmTCHmZKEBhXPN0gmoAq.jpg',
            ],
            [
                'titulo' => 'Cidade de Deus',
                'diretor' => 'Fernando Meirelles, Kátia Lund',
                'ano' => 2002,
                'genero' => 'Crime',
                'sinopse' => 'Nas favelas do Rio de Janeiro, dois rapazes seguem caminhos diferentes: um se torna fotógrafo e o outro um traficante de drogas.',
                'capa' => 'https://media.themoviedb.org/t/p/w300_and_h450_face/gfnXixcGC060QcG6JPxN6AMdVsq.jpg',
            ],
            [
                'titulo' => 'Os Bons Companheiros',
                'diretor' => 'Martin Scorsese',
                'ano' => 1990,
                'genero' => 'Crime',
                'sinopse' => 'A história do jovem Henry Hill e sua ascensão na hierarquia da máfia nova-iorquina ao lado de seus parceiros.',
                'capa' => 'https://image.tmdb.org/t/p/w500/aAC188338sHInI3425f3c9284j2.jpg',
            ],
            [
                'titulo' => 'O Resgate do Soldado Ryan',
                'diretor' => 'Steven Spielberg',
                'ano' => 1998,
                'genero' => 'Guerra',
                'sinopse' => 'Após o Desembarque na Normandia, um grupo de soldados americanos vai atrás das linhas inimigas para resgatar um paraquedista.',
                'capa' => 'https://image.tmdb.org/t/p/w500/132174367373891gkdPOEpXUk5H.jpg',
            ],
            [
                'titulo' => 'A Lista de Schindler',
                'diretor' => 'Steven Spielberg',
                'ano' => 1993,
                'genero' => 'Biografia',
                'sinopse' => 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, Oskar Schindler se preocupa com sua força de trabalho judaica após testemunhar a perseguição.',
                'capa' => 'https://image.tmdb.org/t/p/w500/sF1U4EUNoR39A2V2V327eR1122.jpg',
            ],
            [
                'titulo' => 'O Silêncio dos Inocentes',
                'diretor' => 'Jonathan Demme',
                'ano' => 1991,
                'genero' => 'Suspense',
                'sinopse' => 'Uma jovem estagiária do FBI deve confiar em um assassino manipulador encarcerado para capturar outro serial killer.',
                'capa' => 'https://image.tmdb.org/t/p/w500/rA1p93p44535p3O2rA1p93p4453.jpg',
            ],
            [
                'titulo' => 'Vingadores: Ultimato',
                'diretor' => 'Anthony Russo, Joe Russo',
                'ano' => 2019,
                'genero' => 'Ação',
                'sinopse' => 'Após os eventos devastadores de Guerra Infinita, o universo está em ruínas. Com a ajuda dos aliados restantes, os Vingadores se reúnem novamente.',
                'capa' => 'https://image.tmdb.org/t/p/w500/ul22f67645167232eR1122A1p93.jpg',
            ],
            [
                'titulo' => 'Gladiador',
                'diretor' => 'Ridley Scott',
                'ano' => 2000,
                'genero' => 'Ação',
                'sinopse' => 'Um ex-general romano busca vingança contra o imperador corrupto que assassinou sua família e o enviou para a escravidão.',
                'capa' => 'https://image.tmdb.org/t/p/w500/ty2233f2gL2i5dJpIeP29pL1W12.jpg',
            ],
            [
                'titulo' => 'Parasita',
                'diretor' => 'Bong Joon-ho',
                'ano' => 2019,
                'genero' => 'Suspense',
                'sinopse' => 'A discriminação de classe e a ganância ameaçam o recém-formado relacionamento simbiótico entre a rica família Park e o empobrecido clã Kim.',
                'capa' => 'https://image.tmdb.org/t/p/w500/7IiT21e121e121e121e121e121e.jpg',
            ],
            [
                'titulo' => 'Alien: O Oitavo Passageiro',
                'diretor' => 'Ridley Scott',
                'ano' => 1979,
                'genero' => 'Terror',
                'sinopse' => 'A tripulação de uma nave comercial espacial investiga um sinal de socorro desconhecido e descobre uma forma de vida mortal.',
                'capa' => 'https://image.tmdb.org/t/p/w500/v93538t1A3z6CGMMl0AByR328R2.jpg',
            ],
            [
                'titulo' => 'De Volta para o Futuro',
                'diretor' => 'Robert Zemeckis',
                'ano' => 1985,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Marty McFly, um estudante de ensino médio de 17 anos, é enviado acidentalmente 30 anos no passado em um DeLorean movido a plutônio.',
                'capa' => 'https://image.tmdb.org/t/p/w500/123981298319283912839123891.jpg',
            ],
            [
                'titulo' => 'O Iluminado',
                'diretor' => 'Stanley Kubrick',
                'ano' => 1980,
                'genero' => 'Terror',
                'sinopse' => 'Uma família se muda para um hotel isolado para o inverno, onde uma presença sinistra influencia o pai a cometer violência.',
                'capa' => 'https://image.tmdb.org/t/p/w500/987391283912839128391283912.jpg',
            ],
            [
                'titulo' => 'O Rei Leão',
                'diretor' => 'Roger Allers, Rob Minkoff',
                'ano' => 1994,
                'genero' => 'Animação',
                'sinopse' => 'Um jovem leão herdeiro do trono enfrenta a traição de seu tio e aprende o verdadeiro significado de responsabilidade e coragem.',
                'capa' => 'https://image.tmdb.org/t/p/w500/sHInI3425f3c9284j2aAC188338.jpg',
            ],
            [
                'titulo' => 'Jurassic Park: Parque dos Dinossauros',
                'diretor' => 'Steven Spielberg',
                'ano' => 1993,
                'genero' => 'Aventura',
                'sinopse' => 'Um paleontólogo pragmático visitando um parque temático quase completo na América Central é encarregado de proteger duas crianças após uma falha de energia.',
                'capa' => 'https://image.tmdb.org/t/p/w500/oU7O132174367373891gkdPOEpX.jpg',
            ],
            [
                'titulo' => 'Se7en: Os Sete Crimes Capitais',
                'diretor' => 'David Fincher',
                'ano' => 1995,
                'genero' => 'Crime',
                'sinopse' => 'Dois detetives, um novato e um veterano, caçam um serial killer que usa os sete pecados capitais como seu modus operandi.',
                'capa' => 'https://image.tmdb.org/t/p/w500/GkdPOEpXUk5Hf89U3ADr1oiB1s9.jpg',
            ],
            [
                'titulo' => 'Whiplash: Em Busca da Perfeição',
                'diretor' => 'Damien Chazelle',
                'ano' => 2014,
                'genero' => 'Drama',
                'sinopse' => 'Um jovem e promissor baterista se matricula em um conservatório de música onde seu sonho de grandeza é mentorado por um instrutor impiedoso.',
                'capa' => 'https://image.tmdb.org/t/p/w500/7328R2vQW3538t1A3z6CGMMl0AB.jpg',
            ],
            [
                'titulo' => 'Coringa',
                'diretor' => 'Todd Phillips',
                'ano' => 2019,
                'genero' => 'Drama',
                'sinopse' => 'Em Gotham City, o comediante mentalmente perturbado Arthur Fleck é desconsiderado e maltratado pela sociedade, iniciando uma espiral descendente.',
                'capa' => 'https://image.tmdb.org/t/p/w500/udDclC23188338sHInI3425f3c9.jpg',
            ],
            [
                'titulo' => 'Django Livre',
                'diretor' => 'Quentin Tarantino',
                'ano' => 2012,
                'genero' => 'Faroeste',
                'sinopse' => 'Com a ajuda de um caçador de recompensas alemão, um escravo liberto parte para resgatar sua esposa de um brutal proprietário de plantação no Mississippi.',
                'capa' => 'https://image.tmdb.org/t/p/w500/22gL2i5dJpIeP29pL1WkA234K32.jpg',
            ],
            [
                'titulo' => 'O Show de Truman',
                'diretor' => 'Peter Weir',
                'ano' => 1998,
                'genero' => 'Drama',
                'sinopse' => 'Um vendedor de seguros descobre que toda a sua vida é na verdade um reality show focado inteiramente nele.',
                'capa' => 'https://image.tmdb.org/t/p/w500/p29pL1WkA234K3222gL2i5dJpIe.jpg',
            ],
            [
                'titulo' => 'Titanic',
                'diretor' => 'James Cameron',
                'ano' => 1997,
                'genero' => 'Romance',
                'sinopse' => 'Uma aristocrata de dezessete anos se apaixona por um artista pobre mas gentil a bordo do luxuoso e ilógico R.M.S. Titanic.',
                'capa' => 'https://image.tmdb.org/t/p/w500/912839128391283912839128391.jpg',
            ],
            [
                'titulo' => 'WALL-E',
                'diretor' => 'Andrew Stanton',
                'ano' => 2008,
                'genero' => 'Animação',
                'sinopse' => 'No futuro, um pequeno robô compactador de lixo acidentalmente embarca em uma viagem espacial que decidirá o destino da humanidade.',
                'capa' => 'https://image.tmdb.org/t/p/w500/391283912839128391283912839.jpg',
            ],
            [
                'titulo' => 'O Grande Truque',
                'diretor' => 'Christopher Nolan',
                'ano' => 2006,
                'genero' => 'Mistério',
                'sinopse' => 'Após uma tragédia, dois ilusionistas de palco em Londres se envolvem em uma rivalidade obsessiva para criar a ilusão derradeira.',
                'capa' => 'https://image.tmdb.org/t/p/w500/812839128391283912839128391.jpg',
            ],
            [
                'titulo' => 'Viva: A Vida é uma Festa',
                'diretor' => 'Lee Unkrich, Adrian Molina',
                'ano' => 2017,
                'genero' => 'Animação',
                'sinopse' => 'O aspirante a músico Miguel, confrontado com a proibição ancestral de música em sua família, entra na Terra dos Mortos para encontrar seu ancestral.',
                'capa' => 'https://image.tmdb.org/t/p/w500/7425f3c9284j2aAC188338sHInI.jpg',
            ],
            [
                'titulo' => 'Homem-Aranha: No Aranhaverso',
                'diretor' => 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
                'ano' => 2018,
                'genero' => 'Animação',
                'sinopse' => 'O jovem Miles Morales se torna o Homem-Aranha de seu universo e deve se juntar a cinco indivíduos com poderes de aranha de outras dimensões.',
                'capa' => 'https://image.tmdb.org/t/p/w500/l2i5dJpIeP29pL1WkA234K3222g.jpg',
            ],
            [
                'titulo' => 'Bastardos Inglórios',
                'diretor' => 'Quentin Tarantino',
                'ano' => 2009,
                'genero' => 'Guerra',
                'sinopse' => 'Na França ocupada pelos nazistas, um plano para assassinar os líderes nazistas por um grupo de soldados judeus-americanos coincide com o plano de vingança de uma dona de cinema.',
                'capa' => 'https://image.tmdb.org/t/p/w500/f3c9284j2aAC188338sHInI3425.jpg',
            ],
            [
                'titulo' => 'Psicose',
                'diretor' => 'Alfred Hitchcock',
                'ano' => 1960,
                'genero' => 'Terror',
                'sinopse' => 'Uma secretária de Fênix desvia 40.000 dólares de um cliente de seu patrão, foge e se hospeda em um motel remoto gerado por um jovem sob o domínio de sua mãe.',
                'capa' => 'https://image.tmdb.org/t/p/w500/IeP29pL1WkA234K3222gL2i5dJp.jpg',
            ],
            [
                'titulo' => 'La La Land: Cantando Estações',
                'diretor' => 'Damien Chazelle',
                'ano' => 2016,
                'genero' => 'Musical',
                'sinopse' => 'Enquanto navegam por suas carreiras em Los Angeles, um pianista de jazz e uma aspirante a atriz se apaixonam enquanto tentam conciliar suas aspirações para o futuro.',
                'capa' => 'https://image.tmdb.org/t/p/w500/u12839128391283912839128391.jpg',
            ],
            [
                'titulo' => 'Mad Max: Estrada da Fúria',
                'diretor' => 'George Miller',
                'ano' => 2015,
                'genero' => 'Ação',
                'sinopse' => 'Em uma terra devastada pós-apocalíptica, uma mulher se rebela contra um tirano em busca de sua terra natal com a ajuda de um grupo de prisioneiras e um drifter chamado Max.',
                'capa' => 'https://image.tmdb.org/t/p/w500/3425f3c9284j2aAC188338sHInI.jpg',
            ],
            [
                'titulo' => 'Tropa de Elite',
                'diretor' => 'José Padilha',
                'ano' => 2007,
                'genero' => 'Ação',
                'sinopse' => 'Em 1997, antes da visita do Papa ao Rio de Janeiro, o Capitão Nascimento precisa treinar um substituto enquanto combate o tráfico de drogas.',
                'capa' => 'https://image.tmdb.org/t/p/w500/1WkA234K3222gL2i5dJpIeP29pL.jpg',
            ],
            [
                'titulo' => 'O Fabuloso Destino de Amélie Poulain',
                'diretor' => 'Jean-Pierre Jeunet',
                'ano' => 2001,
                'genero' => 'Comédia',
                'sinopse' => 'Amélie é uma garota inocente e ingênua em Paris com seu próprio senso de justiça. Ela decide ajudar aqueles ao seu redor e descobre o amor ao longo do caminho.',
                'capa' => 'https://image.tmdb.org/t/p/w500/128391283912839128391283912.jpg',
            ],
            [
                'titulo' => 'Psicopata Americano',
                'diretor' => 'Mary Harron',
                'ano' => 2000,
                'genero' => 'Suspense',
                'sinopse' => 'Um rico executivo bancário de investimentos de Nova York esconde seu ego psicopata alternativo de seus colegas enquanto se aprofunda em fantasias violentas.',
                'capa' => 'https://image.tmdb.org/t/p/w500/AC188338sHInI3425f3c9284j2a.jpg',
            ],
            [
                'titulo' => 'Curtindo a Vida Adoidado',
                'diretor' => 'John Hughes',
                'ano' => 1986,
                'genero' => 'Comédia',
                'sinopse' => 'Um garoto do ensino médio finge estar doente para matar aula e passar o dia em Chicago com sua namorada e seu melhor amigo.',
                'capa' => 'https://image.tmdb.org/t/p/w500/234K3222gL2i5dJpIeP29pL1WkA.jpg',
            ],
            [
                'titulo' => 'O Grande Hotel Budapeste',
                'diretor' => 'Wes Anderson',
                'ano' => 2014,
                'genero' => 'Comédia',
                'sinopse' => 'Um famoso gerente de hotel e seu protegido se envolvem no roubo de uma pintura renascentista inestimável e na batalha por uma grande fortuna familiar.',
                'capa' => 'https://image.tmdb.org/t/p/w500/sHInI3425f3c9284j2aAC188338.jpg',
            ],
            [
                'titulo' => 'Brilho Eterno de uma Mente sem Lembranças',
                'diretor' => 'Michel Gondry',
                'ano' => 2004,
                'genero' => 'Romance',
                'sinopse' => 'Quando seu relacionamento se torna azedo, um casal se submete a um procedimento médico para apagar um ao outro de suas memórias.',
                'capa' => 'https://image.tmdb.org/t/p/w500/912839128391283912839128392.jpg',
            ],
            [
                'titulo' => 'Procurando Nemo',
                'diretor' => 'Andrew Stanton, Lee Unkrich',
                'ano' => 2003,
                'genero' => 'Animação',
                'sinopse' => 'Após seu filho ser capturado na Grande Barreira de Corais e levado para Sydney, um peixe-palhaço tímido embarca em uma jornada para trazê-lo de volta.',
                'capa' => 'https://image.tmdb.org/t/p/w500/22gL2i5dJpIeP29pL1WkA234K33.jpg',
            ],
            [
                'titulo' => 'Toy Story',
                'diretor' => 'John Lasseter',
                'ano' => 1995,
                'genero' => 'Animação',
                'sinopse' => 'Um boneco cowboy sente-se ameaçado e enciumado quando um novo robô espacial o substitui como o brinquedo favorito no quarto de um garoto.',
                'capa' => 'https://image.tmdb.org/t/p/w500/pL1WkA234K3222gL2i5dJpIeP29.jpg',
            ],
            [
                'titulo' => 'Star Wars: Episódio V - O Império Contra-Ataca',
                'diretor' => 'Irvin Kershner',
                'ano' => 1980,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Após os rebeldes serem brutalmente sobrepujados pelo Império no planeta gelado Hoth, Luke Skywalker inicia seu treinamento Jedi com Yoda.',
                'capa' => 'https://image.tmdb.org/t/p/w500/7328R2vQW3538t1A3z6CGMMl0AC.jpg',
            ],
            [
                'titulo' => 'Taxi Driver: Motorista de Táxi',
                'diretor' => 'Martin Scorsese',
                'ano' => 1976,
                'genero' => 'Drama',
                'sinopse' => 'Um veterano mentalmente instável da Guerra do Vietnã trabalha como motorista de táxi noturno em Nova York, onde a decadência alimenta seus impulsos violentos.',
                'capa' => 'https://image.tmdb.org/t/p/w500/3425f3c9284j2aAC188338sHInJ.jpg',
            ],
            [
                'titulo' => 'Scarface',
                'diretor' => 'Brian De Palma',
                'ano' => 1983,
                'genero' => 'Crime',
                'sinopse' => 'Em 1980 em Miami, um refugiado cubano determinado assume o controle de um cartel de drogas e sucumbe à ganância e à paranoia.',
                'capa' => 'https://image.tmdb.org/t/p/w500/gL2i5dJpIeP29pL1WkA234K3223.jpg',
            ],
            [
                'titulo' => 'Donnie Darko',
                'diretor' => 'Richard Kelly',
                'ano' => 2001,
                'genero' => 'Ficção Científica',
                'sinopse' => 'Após escapar por pouco de um acidente bizarro, um adolescente problemático tem visões de um homem em uma fantasia de coelho que o manipula a cometer crimes.',
                'capa' => 'https://image.tmdb.org/t/p/w500/812839128391283912839128393.jpg',
            ],
            [
                'titulo' => 'Tubarão',
                'diretor' => 'Steven Spielberg',
                'ano' => 1975,
                'genero' => 'Terror',
                'sinopse' => 'Quando um grande tubarão branco ataca uma comunidade praiana, um chefe de polícia, um biólogo marinho e um caçador de tubarões se unem para caçá-lo.',
                'capa' => 'https://image.tmdb.org/t/p/w500/InI3425f3c9284j2aAC188338sH.jpg',
            ],
            [
                'titulo' => 'Ratatouille',
                'diretor' => 'Brad Bird, Jan Pinkava',
                'ano' => 2007,
                'genero' => 'Animação',
                'sinopse' => 'Um rato que consegue cozinhar faz uma aliança incomum com um jovem ajudante de cozinha em um restaurante famoso de Paris.',
                'capa' => 'https://image.tmdb.org/t/p/w500/4K3222gL2i5dJpIeP29pL1WkA23.jpg',
            ],
            [
                'titulo' => 'Blade Runner 2049',
                'diretor' => 'Denis Villeneuve',
                'ano' => 2017,
                'genero' => 'Ficção Científica',
                'sinopse' => 'O jovem Blade Runner K descobre um segredo há muito enterrado que tem o potencial de mergulhar o que resta da sociedade no caos.',
                'capa' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5G.jpg',
            ],
            [
                'titulo' => 'A Viagem de Chihiro',
                'diretor' => 'Hayao Miyazaki',
                'ano' => 2001,
                'genero' => 'Animação',
                'sinopse' => 'Durante a mudança de sua família para o subúrbio, uma garota de 10 anos vagueia por um mundo governado por deuses, bruxas e espíritos.',
                'capa' => 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Ugf.jpg',
            ],
            [
                'titulo' => 'Logan',
                'diretor' => 'James Mangold',
                'ano' => 2017,
                'genero' => 'Ação',
                'sinopse' => 'Em um futuro próximo, um Wolverine cansado cuida de um Professor X doente em um esconderijo na fronteira com o México.',
                'capa' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WI.jpg',
            ],
            [
                'titulo' => 'O Lobo de Wall Street',
                'diretor' => 'Martin Scorsese',
                'ano' => 2013,
                'genero' => 'Biografia',
                'sinopse' => 'Baseado na história real de Jordan Belfort, desde sua ascensão a um corretor de ações rico vivendo a alta vida até sua queda envolvendo crime e corrupção.',
                'capa' => 'https://image.tmdb.org/t/p/w500/pB8BM2pdSp6B6Ih7QZ4DrQ3PmJL.jpg',
            ],
            [
                'titulo' => '12 Anos de Escravidão',
                'diretor' => 'Steve McQueen',
                'ano' => 2013,
                'genero' => 'Biografia',
                'sinopse' => 'Nos Estados Unidos pré-Guerra Civil, Solomon Northup, um homem negro livre do norte de Nova York, é sequestrado e vendido como escravo.',
                'capa' => 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9L32q3OQB.jpg',
            ],
            [
                'titulo' => 'O Profissional',
                'diretor' => 'Luc Besson',
                'ano' => 1994,
                'genero' => 'Ação',
                'sinopse' => 'Mathilda, uma garota de 12 anos, é acolhida relutantemente por Léon, um assassino profissional, depois que sua família é assassinada.',
                'capa' => 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OPO336OfvO2.jpg',
            ],
            [
                'titulo' => 'Os Suspeitos',
                'diretor' => 'Bryan Singer',
                'ano' => 1995,
                'genero' => 'Crime',
                'sinopse' => 'O único sobrevivente de um massacre em um navio conta à polícia os eventos que levaram cinco criminosos a um roubo aparentemente aleatório.',
                'capa' => 'https://image.tmdb.org/t/p/w500/aAC188338sHInI3425f3c9284j3.jpg',
            ],
            [
                'titulo' => 'Um Sonho de Liberdade',
                'diretor' => 'Frank Darabont',
                'ano' => 1994,
                'genero' => 'Drama',
                'sinopse' => 'Dois homens presos criam um vínculo ao longo de vários anos, encontrando consolo e redenção eventual através de atos de decência comum.',
                'capa' => 'https://image.tmdb.org/t/p/w500/sF1U4EUNoR39A2V2V327eR1123.jpg',
            ],
            [
                'titulo' => 'Oppenheimer',
                'diretor' => 'Christopher Nolan',
                'ano' => 2023,
                'genero' => 'Biografia',
                'sinopse' => 'A história do físico americano J. Robert Oppenheimer e seu papel no Projeto Manhattan, que levou ao desenvolvimento da bomba atômica.',
                'capa' => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGvC46fX333.jpg',
            ],
        ]);
    }
}